user_list:
  path: /api/users
  controller: App\Controller\UserController:indexAction
  methods: [GET]

user_create:
  path: /api/users
  controller: App\Controller\UserController:createAction
  methods: [POST]