register:
  path: /register
  methods: ['POST']
  controller: App\Controller\AuthController::register

# Login check to log the user and generate JWT token
api_login_check:
  path: /login
  methods: [ 'POST' ]